import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer";
import { getHistoricalMessages } from "../lib/history";
import Presence from "../components/Presence";
import Headlines from "../components/Headlines";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ably Realtime News Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          alt="ably logo"
          src="https://static.ably.dev/motif-red.svg?lorem-ipsum"
          width="160px"
          height="100%"
        ></Image>
        <h1>Realtime News</h1>

        <h3>Participants</h3>
        <Presence auth={props.auth} />

        <Headlines history={props.history} />
      </main>

      <Footer />
    </div>
  );
}

export async function getServerSideProps() {
  const historicalMessages = await getHistoricalMessages();
  return {
    props: {
      history: historicalMessages,
    },
  };
}
