import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer";
import Participants from "../components/Participants";
import Articles from "../components/Articles";
import { configureAbly } from "@ably-labs/react-hooks";

configureAbly({ authUrl: `${process.env.NEXT_PUBLIC_HOSTNAME}/api/createTokenRequest` });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ably Realtime News Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image alt="ably logo" src="https://static.ably.dev/motif-red.svg?lorem-ipsum" width="160px" height="100%"></Image>
        <h1>Realtime News</h1>
        <h2>Share your favorite news articles</h2>
        <h3>Participants</h3>
        <Participants />
        <Articles />
      </main>

      <Footer />
    </div>
  );
}
